name: CI Workflow

on:
  push:
    branches:
      - main  # Укажите ветку, для которой будет выполняться CI

jobs:
  build:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4  
        
      - name: Install dependencies
        run: npm install  
        
      - name: Run tests
        run: npm test  
